version: '3.9'

services:

  cloudflaretunnel:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    
    
